export class StudentDtoModel {

adharNo: string;
admissionDate: string;
admissionNo: string;
appKey: string;
bankAccountNo: string;
bankName: string;
batchId: number;
bloodGroup: string;
cast: string;
categoryId: number;
city: string;
classId: number;
currentAddress: string;
disNote: string;
disReasonId: number;
disableAt: string;
dob: string;
email: string;
fatherName: string;
fatherOccupation: string;
fatherPhone: string;
fatherPic: string;
feesDiscount: number;
firstname: string;
gender: string;
guardianAddress: string;
guardianEmail: string;
guardianIs: string;
guardianName: string;
guardianOccupation: string;
guardianPhone: string;
guardianPic: string;
guardianRelation: string;
height: string;
hostelRoomId: number;
id: number;
ifscCode: string;
image: string;
isActive: string;
lastname: string;
measurementDate: string;
mobileno: string;
motherName: string;
motherOccupation: string;
motherPhone: string;
motherPic: string;
note: string;
parentId: number;
permanentAddress: string;
pincode: number;
previousSchool: string;
religion: string;
rollNo: string;
routeId: number;
rte: string;
samagraId: string;
schoolHouseId: number;
sectionId: number;
siblingId: number;
state: string;
transportFees: number;
vehrouteId: number;
weight: string;

    clear() {
        this.adharNo = '';
        this.admissionDate = '';
        this.admissionNo = '';
        this.appKey = '';
        this.bankAccountNo = '';
        this.bankName = '';
        this.batchId = 0;
        this.bloodGroup = '';
        this.cast = '';
        this.categoryId = 0;
        this.city = '';
        this.classId = 0;
        this.currentAddress = '';
        this.disNote = '';
        this.disReasonId = 0;
        this.disableAt = '';
        this.dob = '';
        this.email = '';
        this.fatherName = '';
        this.fatherOccupation = '';
        this.fatherPhone = '';
        this.fatherPic = '';
        this.feesDiscount = 0;
        this.firstname = '';
        this.guardianAddress = '';
        this.guardianEmail = '';
        this.guardianIs = '';
        this.guardianName = '';
        this.guardianOccupation = '';
        this.guardianPhone = '';
        this.guardianPic = '';
        this.guardianRelation = '';
        this.height = '';
        this.hostelRoomId = 0;
        this.id = 0;
        this.ifscCode = '';
        this.image = '';
        this.isActive = '';
        this.lastname = '';
        this.measurementDate = '';
        this.mobileno = '';
        this.motherName = '';
        this.motherOccupation = '';
        this.motherPhone = '';
        this.motherPic = '';
        this.note = '';
        this.parentId = 0;
        this.permanentAddress = '';
        this.pincode = 0;
        this.previousSchool = '';
        this.religion = '';
        this.rollNo = '';
        this.routeId = 0;
        this.rte = '';
        this.samagraId = '';
        this.schoolHouseId = 0;
        this.sectionId = 0;
        this.siblingId = 0;
        this.state = '';
        this.transportFees = 0;
        this.vehrouteId = 0;
        this.weight = '';
    }
}