export class StaffDtoModel {

    accountTitle : string;
    amount	: number
    bankAccountNo : string;
    bankBranch : string;
    bankName	: string;
    basicSalary	: string;
    contactNo	: string;
    contractType	: string;
    dateOfJoining	: string;
    dateOfLeaving	: string;
    departmentId	: number
    departmentName	: string;
    dob	: string;
    email	: string;
    emergencyContactNo	: string;
    employeeId	: string;
    epfNo	: string;
    facebook	: string;
    fatherName	: string;
    gender	: string;
    id	: number
    ifscCode	: string;
    image	: string;
    instagram	: string;
    isActive	: string;
    joiningLetter	: string;
    langId	: number
    linkedin	: string;
    localAddress	: string;
    location	: string;
    maritalStatus	: string;
    motherName	: string;
    name	: string;
    note	: string;
    numberOfLeaves	: number
    otherDocumentFile	: string;
    otherDocumentName	: string;
    password	: string;
    payscale	: string;
    permanentAddress	: string;
    qualification	: string;
    resignationLetter	: string;
    resume	: string;
    roleId	: number
    roleName	: string;
    shift	: string;
    staffDesignation	: string;
    staffDesignationId	: number
    surname	: string;
    twitter	: string;
    userId	: number
    verificationCode	: string;
    workExp	: string;

    clear() {
        this.accountTitle = '';
        this.amount	= 0;
        this.bankAccountNo = '';
        this.bankBranch = '';
        this.bankName	= '';
        this.basicSalary	= '';
        this.contactNo	= '';
        this.contractType	= '';
        this.dateOfJoining	= '';
        this.dateOfLeaving	= '';
        this.departmentId	= 0;
        this.departmentName	= '';
        this.dob	= '';
        this.email	= '';
        this.emergencyContactNo	= '';
        this.employeeId	= '';
        this.epfNo	= '';
        this.facebook	= '';
        this.fatherName	= '';
        this.gender	= '';
        this.id	= 0;
        this.ifscCode	= '';
        this.image	= '';
        this.instagram	= '';
        this.isActive	= '';
        this.joiningLetter	= '';
        this.langId	= 0;
        this.linkedin	= '';
        this.localAddress	= '';
        this.location	= '';
        this.maritalStatus	= '';
        this.motherName	= '';
        this.name	= '';
        this.note	= '';
        this.numberOfLeaves	= 0;
        this.otherDocumentFile	= '';
        this.otherDocumentName	= '';
        this.password	= '';
        this.payscale	= '';
        this.permanentAddress	= '';
        this.qualification	= '';
        this.resignationLetter	= '';
        this.resume	= '';
        this.roleId	= 0;
        this.roleName	= '';
        this.shift	= '';
        this.staffDesignation	= '';
        this.staffDesignationId	= 0;
        this.surname	= '';
        this.twitter	= '';
        this.userId	= 0;
        this.verificationCode	= '';
        this.workExp	= '';
    }
}